import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { passiveLiveMemoryCoherenceUsefulnessWindowProtocol } from '../src/passive-live-memory-coherence-usefulness-window.mjs';
const protocol = passiveLiveMemoryCoherenceUsefulnessWindowProtocol();
assert.equal(protocol.releaseLayer, 'v0.38.0-alpha');
assert.equal(protocol.barrierCrossed, 'bounded_passive_live_memory_coherence_usefulness_window');
assert.equal(protocol.buildsOn, 'v0.37.5_passive_live_memory_coherence_repeatability_scorecard');
assert.equal(protocol.disabledByDefault, true);
assert.equal(protocol.operatorRunOneShotOnly, true);
assert.equal(protocol.localOnly, true);
assert.equal(protocol.passiveOnly, true);
assert.equal(protocol.readOnly, true);
assert.equal(protocol.explicitArtifactsOnly, true);
assert.equal(protocol.acceptsOnlyPinnedCompletedRepeatabilityArtifact, true);
assert.equal(protocol.boundedHumanHandoffUsefulnessWindowOnly, true);
assert.equal(protocol.redactedBeforePersist, true);
assert.equal(protocol.rawSourceCache, 'excluded');
assert.equal(protocol.rawPersisted, false);
assert.equal(protocol.humanReadableReportOnly, true);
assert.equal(protocol.humanReviewOnly, true);
assert.equal(protocol.nonAuthoritative, true);
assert.equal(protocol.recommendationIsAuthority, false);
assert.equal(protocol.agentConsumedOutput, false);
assert.equal(protocol.noMemoryWrites, true);
assert.equal(protocol.noRuntimeIntegration, true);
assert.equal(protocol.policyDecision, null);
mkdirSync('evidence',{recursive:true});
writeFileSync('evidence/passive-live-memory-coherence-usefulness-window-protocol-v0.38.0-alpha.out.json', JSON.stringify({ protocol }, null, 2)+'\n');
