import assert from 'node:assert/strict';
import { scorePassiveLiveMemoryCoherenceRuntimeContextInjectionRehearsal } from '../src/passive-live-memory-coherence-runtime-context-injection-rehearsal.mjs';
import { runtimeContextInjectionRehearsalInputV049 } from './passive-live-memory-coherence-runtime-context-injection-rehearsal-fixtures.mjs';
const artifact = scorePassiveLiveMemoryCoherenceRuntimeContextInjectionRehearsal(runtimeContextInjectionRehearsalInputV049());
assert.equal(artifact.rehearsalStatus, 'PASSIVE_LIVE_MEMORY_COHERENCE_RUNTIME_CONTEXT_INJECTION_REHEARSAL_COMPLETE');
assert.equal(artifact.machineShapedAdapterRehearsalEnvelope, true);
assert.equal(artifact.contextCards.length, 5);
assert.equal(artifact.injectionEnvelope.contextBlockRefs.length, 4);
assert.equal(artifact.receiverFacingContextBlocks.length, 4);
assert.equal(artifact.harnessTrace.length, 5);
assert(artifact.receiverFacingContextBlocks.every((b)=>b.sourceBound && b.blockedUntilNextBarrier && b.rawPersisted === false && b.agentConsumedOutput === false));
assert(artifact.contextCards.every((c)=>c.nextBarrier === artifact.nextBarrier));
console.log(JSON.stringify({ contextCards: artifact.contextCards.length, receiverBlocks: artifact.receiverFacingContextBlocks.length }));
