import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { passiveObservationWindowProtocol, runPassiveObservationWindow } from '../src/passive-observation-window.mjs';
import { passiveObservationWindowInput } from './passive-observation-window-fixtures.mjs';

await mkdir(resolve('evidence'), { recursive: true });
const protocol = passiveObservationWindowProtocol();
assert.equal(protocol.releaseLayer, 'v0.26.0-alpha');
assert.equal(protocol.operatorRunOneShotOnly, true);
assert.equal(protocol.localOnly, true);
assert.equal(protocol.readOnly, true);
assert.equal(protocol.explicitRepoLocalSourcesOnly, true);
assert.equal(protocol.redactionBeforePersist, true);
assert.equal(protocol.nonAuthoritative, true);
assert.equal(protocol.policyDecision, null);
const window = await runPassiveObservationWindow(await passiveObservationWindowInput());
assert.equal(window.windowStatus, 'OBSERVATION_WINDOW_COMPLETE');
assert.equal(window.policyDecision, null);
assert.equal(window.protocol.policyDecision, null);
await writeFile(resolve('evidence/passive-observation-window-protocol-v0.26.0-alpha.out.json'), JSON.stringify({ protocol, windowStatus: window.windowStatus, policyDecision: window.policyDecision }, null, 2) + '\n');
console.log(JSON.stringify({ windowStatus: window.windowStatus }, null, 2));
