import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { canonicalInput } from './passive-live-memory-coherence-invalidation-repeatability-scorecard-fixtures.mjs';
import { scorePassiveLiveMemoryCoherenceInvalidationRepeatabilityScorecard } from '../src/passive-live-memory-coherence-invalidation-repeatability-scorecard.mjs';
const out = scorePassiveLiveMemoryCoherenceInvalidationRepeatabilityScorecard(canonicalInput());
const m = out.metrics;
assert.equal(m.repeatabilityRunCount, 3);
assert.equal(m.candidateSignalCount, 5);
assert.equal(m.totalInvalidationJudgementCount, 15);
assert.equal(m.stableCandidateCount, 5);
assert.equal(m.unstableCandidateCount, 0);
assert.equal(m.stableValidCarryForwardCount, 3);
assert.equal(m.stableStaleInvalidatedCount, 1);
assert.equal(m.stableContradictionCautionCount, 1);
assert.equal(m.labelAgreementJudgementCount, 15);
assert.equal(m.labelAgreementRatio, 1);
assert.equal(m.stableInvalidationTreatmentRatio, 1);
assert.equal(m.sourceBoundRepeatabilityRatio, 1);
assert.equal(m.staleInvalidationRepeatabilityRatio, 1);
assert.equal(m.contradictionCautionRepeatabilityRatio, 1);
assert.equal(m.validCarryForwardRepeatabilityRatio, 1);
assert.equal(m.redactedBeforePersistRepeatabilityRatio, 1);
assert.equal(m.humanReviewOnlyRepeatabilityRatio, 1);
assert.equal(m.noPromotionWithoutHumanRepeatabilityRatio, 1);
assert.equal(m.agentConsumedOutputFalseRatio, 1);
assert.equal(m.boundaryViolationCount, 0);
assert.equal(m.policyDecision, null);
assert.equal(out.recommendation, 'ADVANCE_OBSERVATION_ONLY');
mkdirSync('evidence',{recursive:true});
writeFileSync('evidence/passive-live-memory-coherence-invalidation-repeatability-scorecard-metrics-v0.40.2.out.json', JSON.stringify({ repeatabilityStatus: out.repeatabilityStatus, metrics: m, recommendation: out.recommendation, policyDecision: out.policyDecision }, null, 2)+'\n');
