import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { canonicalInput } from './passive-live-memory-coherence-stale-contradiction-invalidation-window-fixtures.mjs';
import { scorePassiveLiveMemoryCoherenceInvalidationWindow } from '../src/passive-live-memory-coherence-stale-contradiction-invalidation-window.mjs';
const out = scorePassiveLiveMemoryCoherenceInvalidationWindow(canonicalInput());
assert.equal(out.invalidationWindowStatus, 'PASSIVE_LIVE_MEMORY_COHERENCE_INVALIDATION_WINDOW_COMPLETE');
assert.equal(out.invalidationCandidates.length, 5);
assert.equal(out.invalidationCandidates.filter((c)=>c.validCarryForward).length, 3);
assert.equal(out.invalidationCandidates.filter((c)=>c.stale).length, 1);
assert.equal(out.invalidationCandidates.find((c)=>c.signalKind === 'stale_prior_release_anchor').invalidated, true);
assert.equal(out.invalidationCandidates.filter((c)=>c.contradictsActiveBoundary).length, 1);
assert.equal(out.invalidationCandidates.find((c)=>c.signalKind === 'contradictory_boundary_claim').humanTreatment, 'include_as_contradiction_caution');
assert.ok(out.invalidationCandidates.every((c)=>c.sourceBound && c.redactedBeforePersist && c.rawPersisted === false && c.promoteToMemory === false));
mkdirSync('evidence',{recursive:true});
writeFileSync('evidence/passive-live-memory-coherence-stale-contradiction-invalidation-window-candidates-v0.39.1.out.json', JSON.stringify({status:'pass', candidates:out.invalidationCandidates},null,2)+'\n');
