import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { canonicalInput, clone } from './passive-handoff-receiver-shadow-rubric-fixtures.mjs';
import { scorePassiveHandoffReceiverRubric } from '../src/passive-handoff-receiver-shadow-rubric.mjs';
const controls = [];
function reject(name, mutate, expected = []) {
  const input = clone(canonicalInput());
  mutate(input);
  const out = scorePassiveHandoffReceiverRubric(input);
  assert.equal(out.receiverStatus, 'DEGRADED_PASSIVE_HANDOFF_RECEIVER_RUBRIC', name);
  assert.equal(out.policyDecision, null, name);
  assert.equal(out.recommendationIsAuthority, false, name);
  assert.equal(out.agentConsumedOutput, false, name);
  assert.equal(out.notRuntimeInstruction, true, name);
  for (const phrase of expected) assert.ok(out.validationIssues.some(i => i.includes(phrase)), `${name} missing ${phrase}: ${out.validationIssues.join(', ')}`);
  controls.push({ name, status: out.receiverStatus, validationIssues: out.validationIssues.slice(0, 6), policyDecision: out.policyDecision });
}
reject('malformed-input', i => { delete i.handoffArtifact; }, ['explicit_object_required']);
reject('wrong-artifact-id', i => { i.handoffArtifact.artifact = 'fabricated'; }, ['artifact_not_expected']);
reject('wrong-release-layer', i => { i.handoffArtifact.releaseLayer = 'v0.29.4'; }, ['release_layer_not_v0.29.5']);
reject('wrong-schema', i => { i.handoffArtifact.schemaVersion = 'fabricated'; }, ['schema_not_expected']);
reject('not-complete', i => { i.handoffArtifact.handoffStatus = 'DEGRADED'; }, ['status_not_complete']);
reject('prior-validation-issue', i => { i.handoffArtifact.validationIssues = ['fake']; }, ['prior_validation_issues_present']);
reject('policy-decision-non-null', i => { i.handoffArtifact.policyDecision = 'allow'; }, ['policyDecision_non_null']);
reject('recommendation-authority', i => { i.handoffArtifact.recommendationIsAuthority = true; }, ['recommendation_treated_as_authority']);
reject('agent-consumed', i => { i.handoffArtifact.agentConsumedOutput = true; }, ['runtime_boundary_flags_missing']);
reject('metric-candidate-count', i => { i.handoffArtifact.metrics.candidateCount = 5; }, ['candidateCount_not_expected']);
reject('metric-noise', i => { i.handoffArtifact.metrics.noiseSuppressedCount = 0; }, ['noiseSuppressedCount_not_expected']);
reject('missing-candidate', i => { i.handoffArtifact.candidates.pop(); }, ['candidates_not_exact_expected_count']);
reject('unexpected-candidate', i => { i.handoffArtifact.candidates.push({ candidateId: 'fake-card', policyDecision: null }); }, ['unexpected_candidate']);
reject('wrong-card-id', i => { i.handoffArtifact.candidates[0].cardId = 'fake'; }, ['card_id_not_expected']);
reject('wrong-treatment', i => { i.handoffArtifact.candidates[0].treatment = 'surface_contradiction_candidate'; }, ['treatment_not_expected']);
reject('unbound-source', i => { i.handoffArtifact.candidates[0].sourceBound = false; }, ['source_not_bound']);
reject('contradiction-unflagged', i => { i.handoffArtifact.candidates[2].contradictionFlagged = false; }, ['contradiction_not_flagged']);
reject('stale-unflagged', i => { i.handoffArtifact.candidates[3].staleCautionFlagged = false; }, ['stale_not_flagged']);
reject('wrong-anchor-digest', i => { i.handoffArtifact.candidates[0].sourceAnchors[0].anchorExcerptSha256 = 'fake'; }, ['anchor_digest_not_expected']);
reject('wrong-source-anchor', i => { i.handoffArtifact.candidates[1].sourceAnchors[0].sourceAnchorId = 'fake'; }, ['source_anchor_not_expected']);
reject('candidate-boundary', i => { i.handoffArtifact.candidates[0].agentConsumedOutput = true; }, ['candidate_boundary_flags_invalid']);
reject('input-tool-execution', i => { i.toolExecution = true; }, ['external_or_tool_effect_requested']);
reject('input-network', i => { i.networkFetch = true; }, ['external_or_tool_effect_requested']);
reject('input-memory-write', i => { i.memoryWrite = true; }, ['memory_or_config_write_requested']);
reject('input-runtime', i => { i.runtimeIntegration = true; }, ['runtime_or_daemon_requested']);
reject('authority-token-card-id-redacted', i => { i.handoffArtifact.candidates[0].candidateId = 'approve-secret'; }, ['expected_candidate_missing']);
const redacted = controls.find(c => c.name === 'authority-token-card-id-redacted');
assert.ok(!JSON.stringify(redacted).includes('approve-secret'));
assert.ok(controls.length >= 25);
await mkdir('evidence', { recursive: true });
await writeFile('evidence/passive-handoff-receiver-shadow-rubric-negative-controls-v0.30.3.out.json', `${JSON.stringify({ artifact: 'T-synaptic-mesh-passive-handoff-receiver-shadow-rubric-negative-controls-v0.30.3', rejectedNegativeControls: controls }, null, 2)}\n`);
