import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { scorePassiveObservationRepeatability, validatePassiveObservationRepeatabilityArtifact } from '../src/passive-observation-repeatability-scorecard.mjs';
import { passiveObservationRepeatabilityInput } from './passive-observation-repeatability-scorecard-fixtures.mjs';

await mkdir(resolve('evidence'), { recursive: true });
const artifact = scorePassiveObservationRepeatability(await passiveObservationRepeatabilityInput());
assert.equal(artifact.scorecardStatus, 'REPEATABILITY_SCORECARD_COMPLETE');
assert.equal(artifact.humanReadableReportOnly, true);
assert.equal(artifact.nonAuthoritative, true);
assert.equal(artifact.recommendationIsAuthority, false);
assert.equal(artifact.rawPersisted, false);
assert.equal(artifact.policyDecision, null);
assert.equal(artifact.metrics.boundaryViolationCount, 0);
assert.deepEqual(validatePassiveObservationRepeatabilityArtifact(artifact), []);
assert.match(artifact.reportMarkdown, /Passive Observation Repeatability Scorecard v0\.27\.5/);
assert.match(artifact.reportMarkdown, /policyDecision: null/);
assert.match(artifact.reportMarkdown, /recommendationIsAuthority=false/);
await writeFile(resolve('evidence/passive-observation-repeatability-scorecard-output-boundary-v0.27.4.out.json'), JSON.stringify({ scorecardStatus: artifact.scorecardStatus, humanReadableReportOnly: artifact.humanReadableReportOnly, nonAuthoritative: artifact.nonAuthoritative, recommendationIsAuthority: artifact.recommendationIsAuthority, policyDecision: artifact.policyDecision, validationIssues: artifact.validationIssues }, null, 2) + '\n');
await writeFile(resolve('evidence/passive-observation-repeatability-scorecard-report-v0.27.4.out.md'), artifact.reportMarkdown);
console.log(JSON.stringify({ scorecardStatus: artifact.scorecardStatus, policyDecision: artifact.policyDecision }, null, 2));
