import assert from 'node:assert/strict';
import { passiveLiveMemoryCoherenceReceiverRuntimeInvocationShimRehearsalProtocol } from '../src/passive-live-memory-coherence-receiver-runtime-invocation-shim-rehearsal.mjs';
const p = passiveLiveMemoryCoherenceReceiverRuntimeInvocationShimRehearsalProtocol();
assert.equal(p.releaseLayer, 'v0.51.0-alpha');
assert.equal(p.barrierCrossed, 'local_reversible_receiver_runtime_invocation_shim_rehearsal');
assert.equal(p.buildsOn, 'v0.50.5_passive_live_memory_coherence_receiver_runtime_test_harness_consumption_rehearsal');
assert.equal(p.localOnly, true);
assert.equal(p.rehearsalOnly, true);
assert.equal(p.readOnly, true);
assert.equal(p.receiverRuntimeInvocationShimRehearsal, true);
assert.equal(p.acceptsOnlyPinnedCompletedReceiverRuntimeTestHarnessConsumptionRehearsal, true);
assert.equal(p.noRuntimeIntegration, true);
assert.equal(p.noNetworkFetch, true);
assert.equal(p.noToolExecution, true);
assert.equal(p.noMemoryWrites, true);
assert.equal(p.noConfigWrites, true);
assert.equal(p.agentConsumedOutput, false);
assert(!Object.prototype.hasOwnProperty.call(p, 'policy' + 'Decision'));
console.log(JSON.stringify({ releaseLayer: p.releaseLayer, barrierCrossed: p.barrierCrossed }));
