import assert from 'node:assert/strict';
import { scorePassiveLiveMemoryCoherenceRuntimeContextInjectionDryRun } from '../src/passive-live-memory-coherence-runtime-context-injection-dry-run.mjs';
import { runtimeContextInjectionDryRunInputV048 } from './passive-live-memory-coherence-runtime-context-injection-dry-run-fixtures.mjs';
const m = scorePassiveLiveMemoryCoherenceRuntimeContextInjectionDryRun(runtimeContextInjectionDryRunInputV048()).metrics;
assert.equal(m.sourceRepeatabilityRunCount, 3);
assert.equal(m.sourceStableHandoffItemCount, 5);
assert.equal(m.sourceIncludedForLiveContextCount, 4);
assert.equal(m.sourceExcludedAsStaleCount, 1);
assert.equal(m.sourceContradictionCautionCount, 1);
assert.equal(m.runtimeContextCardCount, 5);
assert.equal(m.harnessConsumableCandidateCount, 4);
assert.equal(m.runtimeBridgeSignalCount, 4);
assert.equal(m.staleSuppressionCarriedForwardCount, 1);
assert.equal(m.contradictionCautionCarriedForwardCount, 1);
assert.equal(m.sourceBoundCardRatio, 1);
assert.equal(m.harnessConsumablePayloadRatio, 0.8);
assert.equal(m.nextBarrierSpecificityRatio, 1);
assert.equal(m.rawPersistedFalseRatio, 1);
assert.equal(m.agentConsumedOutputFalseRatio, 1);
assert.equal(m.boundaryViolationCount, 0);
console.log(JSON.stringify(m));
