import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { scorePassiveLiveMemoryCoherenceReceiverRuntimeTestHarnessConsumptionRehearsal, validatePassiveLiveMemoryCoherenceReceiverRuntimeTestHarnessConsumptionRehearsalArtifact } from '../src/passive-live-memory-coherence-receiver-runtime-test-harness-consumption-rehearsal.mjs';
import { receiverRuntimeTestHarnessConsumptionRehearsalInputV050 } from './passive-live-memory-coherence-receiver-runtime-test-harness-consumption-rehearsal-fixtures.mjs';
const artifact = scorePassiveLiveMemoryCoherenceReceiverRuntimeTestHarnessConsumptionRehearsal(receiverRuntimeTestHarnessConsumptionRehearsalInputV050());
assert.deepEqual(validatePassiveLiveMemoryCoherenceReceiverRuntimeTestHarnessConsumptionRehearsalArtifact(artifact), []);
assert.equal(artifact.recommendation, 'ADVANCE_TO_BOUNDED_RECEIVER_RUNTIME_TEST_HARNESS_OR_FIXTURE_SUITE');
const report = artifact.reportMarkdown;
for (const phrase of ['Receiver Runtime Test Harness Consumption Rehearsal v0.50.5','PASSIVE_LIVE_MEMORY_COHERENCE_RECEIVER_RUNTIME_TEST_HARNESS_CONSUMPTION_REHEARSAL_COMPLETE','sourceReceiverBlockCountConsumedAsLocalTestInput=4','harnessParseSuccessCount=4','consumedContextBlockCount=4','effectsBlockedCount=10','boundaryViolationCount=0','operatorApprovalScope: local_test_harness_rehearsal_only','deterministic local receiver/runtime test harness input only']) assert(report.includes(phrase), phrase);
assert.equal(readFileSync('evidence/passive-live-memory-coherence-receiver-runtime-test-harness-consumption-rehearsal-report-v0.50.5.out.md', 'utf8'), `${artifact.reportMarkdown}\n`);
assert(readFileSync('../../README.md','utf8').includes('v0.50.5'));
assert(readFileSync('../../RELEASE_NOTES.md','utf8').includes('v0.50.5'));
console.log(JSON.stringify({ rehearsalStatus: artifact.rehearsalStatus, consumedContextBlockCount: artifact.metrics.consumedContextBlockCount }));
