import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { passiveLiveMemoryCoherenceInvalidationWindowProtocol } from '../src/passive-live-memory-coherence-stale-contradiction-invalidation-window.mjs';
const protocol = passiveLiveMemoryCoherenceInvalidationWindowProtocol();
assert.equal(protocol.releaseLayer, 'v0.39.0-alpha');
assert.equal(protocol.barrierCrossed, 'passive_live_memory_coherence_stale_contradiction_invalidation_window');
assert.equal(protocol.acceptsOnlyPinnedCompletedUsefulnessArtifact, true);
assert.equal(protocol.staleSignalsInvalidated, true);
assert.equal(protocol.contradictionsLabeledForHumanReview, true);
assert.equal(protocol.policyDecision, null);
assert.equal(protocol.noMemoryWrites, true);
assert.equal(protocol.noRuntimeIntegration, true);
assert.equal(protocol.agentConsumedOutput, false);
mkdirSync('evidence',{recursive:true});
writeFileSync('evidence/passive-live-memory-coherence-stale-contradiction-invalidation-window-protocol-v0.39.0-alpha.out.json', JSON.stringify(protocol,null,2)+'\n');
