import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { passiveHardCaseOutcomeRepeatabilityScorecardProtocol } from '../src/passive-hard-case-outcome-repeatability-scorecard.mjs';
const protocol = passiveHardCaseOutcomeRepeatabilityScorecardProtocol();
assert.equal(protocol.releaseLayer, 'v0.35.0-alpha');
assert.equal(protocol.barrierCrossed, 'passive_hard_case_receiver_outcome_repeatability_measurement');
assert.equal(protocol.buildsOn, 'v0.34.5_passive_hard_case_outcome_value_scorecard');
assert.equal(protocol.disabledByDefault, true);
assert.equal(protocol.operatorRunOneShotOnly, true);
assert.equal(protocol.localOnly, true);
assert.equal(protocol.passiveOnly, true);
assert.equal(protocol.readOnly, true);
assert.equal(protocol.explicitArtifactsOnly, true);
assert.equal(protocol.acceptsOnlyPinnedCompletedOutcomeValueArtifact, true);
assert.equal(protocol.producesHumanOutcomeRepeatabilityScorecardOnly, true);
assert.equal(protocol.measuresStableUsefulnessNoiseEvidenceGapLabelsWithoutRuntimeConsumption, true);
assert.equal(protocol.humanReadableReportOnly, true);
assert.equal(protocol.nonAuthoritative, true);
assert.equal(protocol.recommendationIsAuthority, false);
assert.equal(protocol.agentConsumedOutput, false);
assert.equal(protocol.notRuntimeInstruction, true);
assert.equal(protocol.noRuntimeAuthority, true);
assert.equal(protocol.noMemoryWrites, true);
assert.equal(protocol.noRuntimeIntegration, true);
assert.equal(protocol.policyDecision, null);
mkdirSync('evidence',{recursive:true});
writeFileSync('evidence/passive-hard-case-outcome-repeatability-scorecard-protocol-v0.35.0-alpha.out.json', JSON.stringify({ protocol }, null, 2)+'\n');
