import assert from 'node:assert/strict';
import { passiveLiveMemoryCoherenceRuntimeContextInjectionRehearsalProtocol } from '../src/passive-live-memory-coherence-runtime-context-injection-rehearsal.mjs';
const p = passiveLiveMemoryCoherenceRuntimeContextInjectionRehearsalProtocol();
assert.equal(p.releaseLayer, 'v0.49.0-alpha');
assert.equal(p.barrierCrossed, 'local_adapter_live_context_injection_envelope_rehearsal');
assert.equal(p.localOnly, true);
assert.equal(p.rehearsalOnly, true);
assert.equal(p.readOnly, true);
assert.equal(p.machineShapedAdapterRehearsalEnvelope, true);
assert.equal(p.noRuntimeIntegration, true);
assert.equal(p.noNetworkFetch, true);
assert.equal(p.noToolExecution, true);
assert.equal(p.noMemoryWrites, true);
assert.equal(p.noConfigWrites, true);
assert.equal(p.agentConsumedOutput, false);
assert(!Object.prototype.hasOwnProperty.call(p, 'policy' + 'Decision'));
console.log(JSON.stringify({ releaseLayer: p.releaseLayer, barrierCrossed: p.barrierCrossed }));
