import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { passiveLiveMemoryCoherenceObservationRehearsalProtocol } from '../src/passive-live-memory-coherence-observation-rehearsal.mjs';
const protocol = passiveLiveMemoryCoherenceObservationRehearsalProtocol();
assert.equal(protocol.releaseLayer, 'v0.36.0-alpha');
assert.equal(protocol.barrierCrossed, 'passive_live_memory_coherence_observation_rehearsal');
assert.equal(protocol.buildsOn, 'v0.35.5_passive_hard_case_outcome_repeatability_scorecard');
assert.equal(protocol.disabledByDefault, true);
assert.equal(protocol.operatorRunOneShotOnly, true);
assert.equal(protocol.localOnly, true);
assert.equal(protocol.passiveOnly, true);
assert.equal(protocol.readOnly, true);
assert.equal(protocol.explicitSourcesOnly, true);
assert.equal(protocol.repoLocalSourcesOnly, true);
assert.equal(protocol.acceptsOnlyPinnedCompletedRepeatabilityArtifact, true);
assert.equal(protocol.redactedBeforePersist, true);
assert.equal(protocol.rawSourceCache, 'excluded');
assert.equal(protocol.rawPersisted, false);
assert.equal(protocol.producesHumanMemoryCoherenceObservationOnly, true);
assert.equal(protocol.humanReadableReportOnly, true);
assert.equal(protocol.nonAuthoritative, true);
assert.equal(protocol.recommendationIsAuthority, false);
assert.equal(protocol.agentConsumedOutput, false);
assert.equal(protocol.noMemoryWrites, true);
assert.equal(protocol.noRuntimeIntegration, true);
assert.equal(protocol.policyDecision, null);
mkdirSync('evidence',{recursive:true});
writeFileSync('evidence/passive-live-memory-coherence-observation-rehearsal-protocol-v0.36.0-alpha.out.json', JSON.stringify({ protocol }, null, 2)+'\n');
