import assert from 'node:assert/strict';
import { writeFileSync, mkdirSync } from 'node:fs';
import { canonicalInput } from './passive-context-assembly-rehearsal-scorecard-fixtures.mjs';
import { scorePassiveContextAssemblyRehearsalScorecard } from '../src/passive-context-assembly-rehearsal-scorecard.mjs';
const out=scorePassiveContextAssemblyRehearsalScorecard(canonicalInput());
assert.equal(out.assemblyStatus,'PASSIVE_CONTEXT_ASSEMBLY_REHEARSAL_SCORECARD_COMPLETE');
assert.equal(out.assemblyItems.length,4);
assert.equal(out.assemblyItems.filter(i=>i.includeForHumanContext).length,2);
assert.equal(out.assemblyItems.filter(i=>i.surfaceConflictForHumanReview).length,1);
assert.equal(out.assemblyItems.filter(i=>i.includeAsStaleCaution).length,1);
assert.ok(out.assemblyItems.every(i=>i.humanReviewOnly && i.promoteToMemory===false && i.policyDecision===null));
mkdirSync('evidence',{recursive:true}); writeFileSync('evidence/passive-context-assembly-rehearsal-scorecard-assembly-v0.32.1.out.json', JSON.stringify({assemblyStatus:out.assemblyStatus,assemblyItems:out.assemblyItems},null,2)+'\n');
