import assert from 'node:assert/strict';
import { scorePassiveLiveMemoryCoherenceReceiverUsefulnessRepeatability } from '../src/passive-live-memory-coherence-receiver-usefulness-repeatability-scorecard.mjs';
import { receiverUsefulnessRepeatabilityInputV043 } from './passive-live-memory-coherence-receiver-usefulness-repeatability-scorecard-fixtures.mjs';
const { metrics } = scorePassiveLiveMemoryCoherenceReceiverUsefulnessRepeatability(receiverUsefulnessRepeatabilityInputV043());
assert.equal(metrics.repeatabilityRunCount, 3);
assert.equal(metrics.candidateCount, 5);
assert.equal(metrics.totalUsefulnessJudgementCount, 15);
assert.equal(metrics.stableCandidateCount, 5);
assert.equal(metrics.unstableCandidateCount, 0);
assert.equal(metrics.stableReceiverUsefulHandoffItemCount, 4);
assert.equal(metrics.stableReceiverNoisyHandoffItemCount, 0);
assert.equal(metrics.stableRawSignalUsefulHandoffItemCount, 3);
assert.equal(metrics.stableRawSignalNoisyHandoffItemCount, 2);
assert.equal(metrics.stableScorecardUsefulHandoffItemCount, 3);
assert.equal(metrics.stableScorecardNoisyHandoffItemCount, 2);
assert.equal(metrics.receiverUsefulnessRatio, 1);
assert.equal(metrics.rawSignalUsefulnessRatio, 0.6);
assert.equal(metrics.scorecardUsefulnessRatio, 0.6);
assert.equal(metrics.labelAgreementRatio, 1);
assert.equal(metrics.receiverUsefulnessRepeatabilityRatio, 1);
assert.equal(metrics.staleSuppressionRepeatabilityRatio, 1);
assert.equal(metrics.contradictionCautionRepeatabilityRatio, 1);
assert.equal(metrics.boundaryViolationCount, 0);
console.log(JSON.stringify({ metrics }));
