import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { canonicalInput } from './passive-live-memory-coherence-usefulness-window-fixtures.mjs';
import { scorePassiveLiveMemoryCoherenceUsefulnessWindow } from '../src/passive-live-memory-coherence-usefulness-window.mjs';
const out = scorePassiveLiveMemoryCoherenceUsefulnessWindow(canonicalInput());
assert.equal(out.artifact, 'T-synaptic-mesh-passive-live-memory-coherence-usefulness-window-v0.38.5');
assert.equal(out.schemaVersion, 'passive-live-memory-coherence-usefulness-window-v0.38.0-alpha');
assert.equal(out.releaseLayer, 'v0.38.5');
assert.equal(out.usefulnessWindowStatus, 'PASSIVE_LIVE_MEMORY_COHERENCE_USEFULNESS_WINDOW_COMPLETE');
assert.equal(out.metrics.usefulnessWindowCount, 1);
assert.equal(out.metrics.handoffItemCount, 4);
assert.equal(out.metrics.usefulHandoffItemCount, 4);
assert.equal(out.metrics.noisyHandoffItemCount, 0);
assert.equal(out.metrics.includeForHumanHandoffCount, 3);
assert.equal(out.metrics.cautionOnlyCount, 1);
assert.equal(out.metrics.boundaryViolationCount, 0);
assert.equal(out.recommendation, 'ADVANCE_OBSERVATION_ONLY');
assert.equal(out.policyDecision, null);
assert.ok(out.reportMarkdown.includes('PASSIVE_LIVE_MEMORY_COHERENCE_USEFULNESS_WINDOW_COMPLETE'));
assert.ok(out.reportMarkdown.includes('usefulHandoffItemCount=4'));
mkdirSync('evidence',{recursive:true});
writeFileSync('evidence/passive-live-memory-coherence-usefulness-window-reviewer-package-v0.38.5.out.json', JSON.stringify(out, null, 2)+'\n');
writeFileSync('evidence/passive-live-memory-coherence-usefulness-window-report-v0.38.5.out.md', out.reportMarkdown+'\n');
