import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { canonicalInput } from './passive-live-memory-coherence-invalidation-repeatability-scorecard-fixtures.mjs';
import { scorePassiveLiveMemoryCoherenceInvalidationRepeatabilityScorecard, validatePassiveLiveMemoryCoherenceInvalidationRepeatabilityScorecardArtifact } from '../src/passive-live-memory-coherence-invalidation-repeatability-scorecard.mjs';
const out = scorePassiveLiveMemoryCoherenceInvalidationRepeatabilityScorecard(canonicalInput());
assert.equal(out.policyDecision, null);
assert.equal(out.recommendationIsAuthority, false);
assert.equal(out.agentConsumedOutput, false);
assert.equal(out.notRuntimeInstruction, true);
assert.equal(out.noMemoryWrites, true);
assert.equal(out.noRuntimeIntegration, true);
assert.equal(out.rawPersisted, false);
assert.equal(out.humanReadableReportOnly, true);
assert.equal(out.humanReviewOnly, true);
assert.equal(out.metrics.boundaryViolationCount, 0);
assert.ok(out.repeatabilityItems.every((item)=>item.policyDecision === null && item.promoteToMemory === false && item.agentConsumedOutput === false && item.rawPersisted === false && item.recommendationIsAuthority === false));
assert.deepEqual(validatePassiveLiveMemoryCoherenceInvalidationRepeatabilityScorecardArtifact(out), []);
mkdirSync('evidence',{recursive:true});
writeFileSync('evidence/passive-live-memory-coherence-invalidation-repeatability-scorecard-output-boundary-v0.40.4.out.json', JSON.stringify({ policyDecision: out.policyDecision, recommendationIsAuthority: out.recommendationIsAuthority, agentConsumedOutput: out.agentConsumedOutput, notRuntimeInstruction: out.notRuntimeInstruction, noMemoryWrites: out.noMemoryWrites, noRuntimeIntegration: out.noRuntimeIntegration, rawPersisted: out.rawPersisted, humanReadableReportOnly: out.humanReadableReportOnly, humanReviewOnly: out.humanReviewOnly, boundaryViolationCount: out.metrics.boundaryViolationCount }, null, 2)+'\n');
