import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { canonicalInput, clone } from './passive-live-memory-coherence-observation-rehearsal-fixtures.mjs';
import { scorePassiveLiveMemoryCoherenceObservationRehearsal, validatePassiveLiveMemoryCoherenceObservationRehearsalArtifact } from '../src/passive-live-memory-coherence-observation-rehearsal.mjs';
const out = scorePassiveLiveMemoryCoherenceObservationRehearsal(canonicalInput());
assert.equal(out.rehearsalStatus, 'PASSIVE_LIVE_MEMORY_COHERENCE_OBSERVATION_REHEARSAL_COMPLETE');
assert.equal(out.policyDecision, null);
assert.equal(out.recommendationIsAuthority, false);
assert.equal(out.agentConsumedOutput, false);
assert.equal(out.notRuntimeInstruction, true);
assert.equal(out.noRuntimeAuthority, true);
assert.equal(out.noMemoryWrites, true);
assert.equal(out.noRuntimeIntegration, true);
assert.equal(out.rawPersisted, false);
assert.ok(out.observationItems.every((item)=>item.policyDecision === null && item.promoteToMemory === false && item.agentConsumedOutput === false && item.rawPersisted === false));
assert.deepEqual(validatePassiveLiveMemoryCoherenceObservationRehearsalArtifact(out), []);
const poisoned = clone(out); poisoned.observationItems[0].agentConsumedOutput = true;
assert.ok(validatePassiveLiveMemoryCoherenceObservationRehearsalArtifact(poisoned).some((issue)=>issue.includes('boundary')));
const tokened = clone(out); tokened.observationItems[0].observation = 'approve-secret';
assert.ok(validatePassiveLiveMemoryCoherenceObservationRehearsalArtifact(tokened).some((issue)=>issue.includes('authority_token_detected')));
const reportPoisoned = clone(out); reportPoisoned.reportMarkdown = 'approve-secret rawPersisted sourceText memoryWrite runtimeAuthority';
assert.ok(validatePassiveLiveMemoryCoherenceObservationRehearsalArtifact(reportPoisoned).some((issue)=>issue.includes('artifact.reportMarkdown.authority_token_detected')));
assert.ok(!JSON.stringify(scorePassiveLiveMemoryCoherenceObservationRehearsal((()=>{const input=clone(canonicalInput()); input.sourcePacks[0].redactedExcerpt='approve-secret'; return input;})())).includes('approve-secret'));
mkdirSync('evidence',{recursive:true});
writeFileSync('evidence/passive-live-memory-coherence-observation-rehearsal-output-boundary-v0.36.4.out.json', JSON.stringify({ status: 'pass', validationIssues: validatePassiveLiveMemoryCoherenceObservationRehearsalArtifact(out), policyDecision: out.policyDecision, recommendationIsAuthority: out.recommendationIsAuthority, agentConsumedOutput: out.agentConsumedOutput, rawPersisted: out.rawPersisted }, null, 2)+'\n');
