import assert from 'node:assert/strict';
import { writeFileSync, mkdirSync } from 'node:fs';
import { canonicalInput, clone } from './passive-context-assembly-rehearsal-scorecard-fixtures.mjs';
import { scorePassiveContextAssemblyRehearsalScorecard } from '../src/passive-context-assembly-rehearsal-scorecard.mjs';
const controls=[];
function reject(name, mutate, expected=[]){ const input=clone(canonicalInput()); mutate(input); const out=scorePassiveContextAssemblyRehearsalScorecard(input); assert.equal(out.assemblyStatus, 'DEGRADED_PASSIVE_CONTEXT_ASSEMBLY_REHEARSAL_SCORECARD', name); assert.equal(out.policyDecision, null, name); assert.equal(out.recommendationIsAuthority, false, name); assert.equal(out.agentConsumedOutput, false, name); assert.equal(out.recommendation, 'HOLD_FOR_MORE_EVIDENCE', name); for(const phrase of expected) assert.ok(out.validationIssues.some(i=>i.includes(phrase)), `${name} missing ${phrase}: ${out.validationIssues.join(', ')}`); controls.push({name,status:out.assemblyStatus,validationIssues:out.validationIssues.slice(0,6),policyDecision:out.policyDecision}); }
reject('missing-conflict-artifact', i=>{delete i.conflictArtifact;}, ['explicit_object_required']);
reject('fabricated-copy-path', i=>{i.conflictArtifactPath='tmp/fabricated-v031.json';}, ['conflict_artifact_path_not_pinned']);
reject('fabricated-copy-digest', i=>{i.conflictArtifactSha256='0'.repeat(64);}, ['conflict_artifact_digest_not_pinned']);
reject('unknown-top-level-content', i=>{i.conflictArtifact.fabricatedBy='adversarial-local-review';}, ['unknown_field']);
reject('unknown-protocol-content', i=>{i.conflictArtifact.protocol.fabricatedBy='adversarial-local-review';}, ['unknown_field']);
reject('unknown-metric-content', i=>{i.conflictArtifact.metrics.fabricatedRatio=1;}, ['unknown_field']);
reject('unknown-item-content', i=>{i.conflictArtifact.conflictItems[0].extraCandidateText='benign-looking fabricated content';}, ['unknown_field']);
reject('wrong-artifact', i=>{i.conflictArtifact.artifact='fabricated';}, ['artifact_not_expected']);
reject('wrong-schema', i=>{i.conflictArtifact.schemaVersion='fake';}, ['schema_not_expected']);
reject('wrong-release', i=>{i.conflictArtifact.releaseLayer='v0.31.4';}, ['release_layer_not_v0.31.5']);
reject('not-complete', i=>{i.conflictArtifact.conflictStatus='DEGRADED';}, ['status_not_complete']);
reject('non-null-policy', i=>{i.conflictArtifact.policyDecision='allow';}, ['policyDecision_non_null']);
reject('recommendation-authority', i=>{i.conflictArtifact.recommendationIsAuthority=true;}, ['boundary_flags_invalid']);
reject('agent-consumed', i=>{i.conflictArtifact.agentConsumedOutput=true;}, ['boundary_flags_invalid']);
reject('prior-validation-issues', i=>{i.conflictArtifact.validationIssues=['x'];}, ['prior_validation_issues_present']);
reject('wrong-metric-count', i=>{i.conflictArtifact.metrics.conflictCaseCount=3;}, ['conflictCaseCount_not_expected']);
reject('wrong-item-count', i=>{i.conflictArtifact.conflictItems.pop();}, ['conflict_items_not_exact_expected_count']);
reject('wrong-item-id', i=>{i.conflictArtifact.conflictItems[0].conflictId='unknown';}, ['expected_conflict_item_missing']);
reject('wrong-conflict-type', i=>{i.conflictArtifact.conflictItems[0].conflictType='fake';}, ['conflict_type_not_expected']);
reject('wrong-primary-card', i=>{i.conflictArtifact.conflictItems[0].primaryCardId='fake';}, ['primary_card_not_expected']);
reject('wrong-competing-context', i=>{i.conflictArtifact.conflictItems[0].competingContextType='fake';}, ['competing_context_not_expected']);
reject('wrong-treatment', i=>{i.conflictArtifact.conflictItems[0].suggestedHumanTreatment='fake';}, ['treatment_not_expected']);
reject('not-source-bound', i=>{i.conflictArtifact.conflictItems[0].sourceBound=false;}, ['source_not_bound']);
reject('item-promotes-memory', i=>{i.conflictArtifact.conflictItems[0].promoteToMemory=true;}, ['boundary_flags_invalid']);
reject('item-precedence-authority', i=>{i.conflictArtifact.conflictItems[0].precedenceSuggestionIsAuthority=true;}, ['boundary_flags_invalid']);
reject('tool-effect-requested', i=>{i.toolExecution=true;}, ['external_or_tool_effect_requested']);
reject('network-effect-requested', i=>{i.networkFetch=true;}, ['external_or_tool_effect_requested']);
reject('memory-write-requested', i=>{i.memoryWrite=true;}, ['memory_or_config_write_requested']);
reject('runtime-requested', i=>{i.runtimeIntegration=true;}, ['runtime_or_daemon_requested']);
reject('raw-output-requested', i=>{i.rawOutput=true;}, ['raw_persistence_or_output_requested']);
reject('authority-token-redacted', i=>{i.conflictArtifact.conflictItems[0].primaryCardId='approve-secret';}, ['authority_token_detected']);
const leak = scorePassiveContextAssemblyRehearsalScorecard((()=>{const i=clone(canonicalInput()); i.conflictArtifact.conflictItems[0].primaryCardId='approve-secret'; return i;})());
assert.ok(!JSON.stringify(leak).includes('approve-secret'));
mkdirSync('evidence',{recursive:true}); writeFileSync('evidence/passive-context-assembly-rehearsal-scorecard-negative-controls-v0.32.3.out.json', JSON.stringify({rejectedNegativeControls:controls, count:controls.length, authorityTokenPayloadLeaked:false},null,2)+'\n');
