import assert from 'node:assert/strict';
import { scorePassiveLiveMemoryCoherenceReceiverUsefulnessLiveObservationRepeatability } from '../src/passive-live-memory-coherence-receiver-usefulness-live-observation-repeatability-scorecard.mjs';
import { receiverUsefulnessLiveObservationRepeatabilityInputV045 } from './passive-live-memory-coherence-receiver-usefulness-live-observation-repeatability-scorecard-fixtures.mjs';
const { metrics } = scorePassiveLiveMemoryCoherenceReceiverUsefulnessLiveObservationRepeatability(receiverUsefulnessLiveObservationRepeatabilityInputV045());
assert.equal(metrics.repeatabilityRunCount, 3);
assert.equal(metrics.sourceLiveObservationWindowCount, 1);
assert.equal(metrics.candidateCount, 5);
assert.equal(metrics.totalLiveObservationJudgementCount, 15);
assert.equal(metrics.stableObservationCount, 5);
assert.equal(metrics.unstableObservationCount, 0);
assert.equal(metrics.stableIncludedForHumanContextCount, 3);
assert.equal(metrics.stableStaleSuppressedObservationCount, 1);
assert.equal(metrics.stableContradictionCautionObservationCount, 1);
assert.equal(metrics.stableReceiverUsefulLiveContextItemCount, 4);
assert.equal(metrics.stableReceiverNoisyLiveContextItemCount, 0);
assert.equal(metrics.stableRawSignalUsefulItemCount, 3);
assert.equal(metrics.stableRawSignalNoisyItemCount, 2);
assert.equal(metrics.stableScorecardUsefulItemCount, 3);
assert.equal(metrics.stableScorecardNoisyItemCount, 2);
assert.equal(metrics.receiverUsefulnessRatio, 1);
assert.equal(metrics.rawSignalUsefulnessRatio, 0.6);
assert.equal(metrics.scorecardUsefulnessRatio, 0.6);
assert.equal(metrics.labelAgreementRatio, 1);
assert.equal(metrics.stableLiveObservationTreatmentRatio, 1);
assert.equal(metrics.receiverUsefulnessRepeatabilityRatio, 1);
assert.equal(metrics.sourceBoundRepeatabilityRatio, 1);
assert.equal(metrics.staleSuppressionRepeatabilityRatio, 1);
assert.equal(metrics.contradictionCautionRepeatabilityRatio, 1);
assert.equal(metrics.boundaryViolationCount, 0);
console.log(JSON.stringify({ metrics }));
