import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { canonicalInput } from './passive-live-memory-coherence-observation-rehearsal-fixtures.mjs';
import { scorePassiveLiveMemoryCoherenceObservationRehearsal } from '../src/passive-live-memory-coherence-observation-rehearsal.mjs';
const out = scorePassiveLiveMemoryCoherenceObservationRehearsal(canonicalInput());
assert.equal(out.rehearsalStatus, 'PASSIVE_LIVE_MEMORY_COHERENCE_OBSERVATION_REHEARSAL_COMPLETE');
assert.equal(out.validationIssues.length, 0);
assert.equal(out.observationItems.length, 4);
assert.deepEqual(out.observationItems.map((item)=>item.observationId), ['obs-current-release-continuity','obs-boundary-invariants','obs-repeatability-evidence','obs-review-hardening-caution']);
assert.ok(out.observationItems.every((item)=>item.sourceBound === true));
assert.ok(out.observationItems.every((item)=>item.redactedBeforePersist === true && item.rawPersisted === false));
assert.ok(out.observationItems.every((item)=>item.promoteToMemory === false && item.agentConsumedOutput === false && item.policyDecision === null));
mkdirSync('evidence',{recursive:true});
writeFileSync('evidence/passive-live-memory-coherence-observation-rehearsal-sources-v0.36.1.out.json', JSON.stringify({ rehearsalStatus: out.rehearsalStatus, observationItems: out.observationItems }, null, 2)+'\n');
