import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { passiveObservationRepeatabilityProtocol, scorePassiveObservationRepeatability } from '../src/passive-observation-repeatability-scorecard.mjs';
import { passiveObservationRepeatabilityInput } from './passive-observation-repeatability-scorecard-fixtures.mjs';

await mkdir(resolve('evidence'), { recursive: true });
const protocol = passiveObservationRepeatabilityProtocol();
assert.equal(protocol.releaseLayer, 'v0.27.0-alpha');
assert.equal(protocol.localOnly, true);
assert.equal(protocol.passiveOnly, true);
assert.equal(protocol.readOnly, true);
assert.equal(protocol.explicitArtifactsOnly, true);
assert.equal(protocol.acceptsOnlyRedactedV026WindowArtifacts, true);
assert.equal(protocol.recommendationIsAuthority, false);
assert.equal(protocol.policyDecision, null);
const scorecard = scorePassiveObservationRepeatability(await passiveObservationRepeatabilityInput());
assert.equal(scorecard.scorecardStatus, 'REPEATABILITY_SCORECARD_COMPLETE');
assert.equal(scorecard.policyDecision, null);
await writeFile(resolve('evidence/passive-observation-repeatability-scorecard-protocol-v0.27.0-alpha.out.json'), JSON.stringify({ protocol, scorecardStatus: scorecard.scorecardStatus, policyDecision: scorecard.policyDecision }, null, 2) + '\n');
console.log(JSON.stringify({ scorecardStatus: scorecard.scorecardStatus }, null, 2));
