import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { passiveLiveMemoryCoherenceInvalidationRepeatabilityScorecardProtocol } from '../src/passive-live-memory-coherence-invalidation-repeatability-scorecard.mjs';
const protocol = passiveLiveMemoryCoherenceInvalidationRepeatabilityScorecardProtocol();
assert.equal(protocol.releaseLayer, 'v0.40.0-alpha');
assert.equal(protocol.barrierCrossed, 'passive_live_memory_coherence_invalidation_repeatability_scorecard');
assert.equal(protocol.buildsOn, 'v0.39.5_passive_live_memory_coherence_stale_contradiction_invalidation_window');
assert.equal(protocol.acceptsOnlyPinnedCompletedInvalidationArtifact, true);
assert.equal(protocol.repeatedInvalidationJudgementsOnly, true);
assert.equal(protocol.staleInvalidationRepeatabilityOnly, true);
assert.equal(protocol.contradictionCautionRepeatabilityOnly, true);
assert.equal(protocol.localOnly, true);
assert.equal(protocol.passiveOnly, true);
assert.equal(protocol.readOnly, true);
assert.equal(protocol.redactedBeforePersist, true);
assert.equal(protocol.rawPersisted, false);
assert.equal(protocol.humanReadableReportOnly, true);
assert.equal(protocol.humanReviewOnly, true);
assert.equal(protocol.nonAuthoritative, true);
assert.equal(protocol.agentConsumedOutput, false);
assert.equal(protocol.noMemoryWrites, true);
assert.equal(protocol.noRuntimeIntegration, true);
assert.equal(protocol.policyDecision, null);
mkdirSync('evidence',{recursive:true});
writeFileSync('evidence/passive-live-memory-coherence-invalidation-repeatability-scorecard-protocol-v0.40.0-alpha.out.json', JSON.stringify(protocol,null,2)+'\n');
