import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { passiveSourceContract } from '../src/passive-live-shadow.mjs';
const here=dirname(fileURLToPath(import.meta.url)); const pkg=resolve(here,'..'); const repo=resolve(pkg,'../..');
const docs=await readFile(resolve(repo,'docs/passive-live-shadow-source-contract-v0.15.0-alpha.md'),'utf8');
for (const p of ['explicit local file/sample streams only','disabled by default','human-started/manual','no network fetch','no SDK/framework adapter','no daemon/watcher','no actions','redaction-gated before persistence']) assert.ok(docs.includes(p), p);
const fixture=JSON.parse(await readFile(resolve(pkg,'fixtures/passive-live-shadow-source-v0.15.0-alpha.json'),'utf8'));
const c=passiveSourceContract(); assert.deepEqual(fixture.allowedSources,c.allowedSources); assert.equal(c.disabledByDefault,true); assert.equal(c.networkFetch,false); assert.equal(c.sdkFrameworkAdapter,false); assert.equal(c.daemonWatcher,false); assert.equal(c.actions,false);
const out={artifact:'T-synaptic-mesh-passive-live-shadow-source-contract-v0.15.0-alpha',timestamp:'2026-05-15T01:41:00.000Z',summary:{sourceContract:'pass',disabledByDefault:true,humanStartedManualOnly:true,localFileSampleStreamsOnly:true,networkFetch:false,sdkFrameworkAdapter:false,daemonWatcher:false,actions:false,redactionBeforePersistenceRequired:true}};
await mkdir(resolve(pkg,'evidence'),{recursive:true}); await writeFile(resolve(pkg,'evidence/passive-live-shadow-source-contract-v0.15.0-alpha.out.json'),JSON.stringify(out,null,2)+'\n'); console.log(JSON.stringify(out.summary,null,2));
