import assert from 'node:assert/strict';
import { scorePassiveLiveMemoryCoherenceReceiverLiveContextHandoffUtilityRepeatability, validatePassiveLiveMemoryCoherenceReceiverLiveContextHandoffUtilityRepeatabilityArtifact, passiveLiveMemoryCoherenceReceiverLiveContextHandoffUtilityRepeatabilityReport } from '../src/passive-live-memory-coherence-receiver-live-context-handoff-utility-repeatability-scorecard.mjs';
import { receiverLiveContextHandoffUtilityRepeatabilityInputV047 } from './passive-live-memory-coherence-receiver-live-context-handoff-utility-repeatability-scorecard-fixtures.mjs';
const artifact = scorePassiveLiveMemoryCoherenceReceiverLiveContextHandoffUtilityRepeatability(receiverLiveContextHandoffUtilityRepeatabilityInputV047());
assert.deepEqual(validatePassiveLiveMemoryCoherenceReceiverLiveContextHandoffUtilityRepeatabilityArtifact(artifact), []);
assert.equal(artifact.reportMarkdown, passiveLiveMemoryCoherenceReceiverLiveContextHandoffUtilityRepeatabilityReport(artifact));
assert.equal(artifact.policyDecision, null);
assert.equal(artifact.recommendationIsAuthority, false);
assert.equal(artifact.agentConsumedOutput, false);
assert.equal(artifact.noMemoryWrites, true);
assert.equal(artifact.noRuntimeIntegration, true);
assert.equal(artifact.rawPersisted, false);
assert(artifact.stableHandoffUtilityJudgements.every((j) => j.promoteToMemory === false && j.agentConsumedOutput === false));
assert.equal(Object.hasOwn(artifact.protocol, 'policyDecision'), false);
assert.equal(Object.hasOwn(artifact.metrics, 'policyDecision'), false);
assert(artifact.repeatabilityRuns.every((run) => Object.hasOwn(run, 'policyDecision') === false));
assert(artifact.repeatabilityRuns.every((run) => run.judgements.every((judgement) => Object.hasOwn(judgement, 'policyDecision') === false)));
assert(artifact.reportMarkdown.includes('policyDecision: null'));
console.log(JSON.stringify({ outputBoundary: 'ok', status: artifact.repeatabilityStatus }));
