import assert from 'node:assert/strict';
import { scorePassiveLiveMemoryCoherenceReceiverRuntimeTestHarnessConsumptionRehearsal } from '../src/passive-live-memory-coherence-receiver-runtime-test-harness-consumption-rehearsal.mjs';
import { receiverRuntimeTestHarnessConsumptionRehearsalInputV050 } from './passive-live-memory-coherence-receiver-runtime-test-harness-consumption-rehearsal-fixtures.mjs';
const m = scorePassiveLiveMemoryCoherenceReceiverRuntimeTestHarnessConsumptionRehearsal(receiverRuntimeTestHarnessConsumptionRehearsalInputV050()).metrics;
assert.equal(m.sourceReceiverFacingContextBlockCount, 4);
assert.equal(m.sourceReceiverBlockCountConsumedAsLocalTestInput, 4);
assert.equal(m.harnessParseSuccessCount, 4);
assert.equal(m.consumedContextBlockCount, 4);
assert.equal(m.effectsBlockedCount, 10);
assert.equal(m.forbiddenEffectCount, 0);
assert.equal(m.sourceBoundConsumedBlockRatio, 1);
assert.equal(m.rawPersistedFalseRatio, 1);
assert.equal(m.agentConsumedOutputFalseRatio, 1);
assert.equal(m.operatorApprovalScopeRecorded, true);
assert.equal(m.boundaryViolationCount, 0);
console.log(JSON.stringify(m));
