import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { scorePassiveLiveMemoryCoherenceReceiverUsefulnessRepeatability, validatePassiveLiveMemoryCoherenceReceiverUsefulnessRepeatabilityArtifact } from '../src/passive-live-memory-coherence-receiver-usefulness-repeatability-scorecard.mjs';
import { receiverUsefulnessRepeatabilityInputV043 } from './passive-live-memory-coherence-receiver-usefulness-repeatability-scorecard-fixtures.mjs';
const artifact = scorePassiveLiveMemoryCoherenceReceiverUsefulnessRepeatability(receiverUsefulnessRepeatabilityInputV043());
assert.deepEqual(validatePassiveLiveMemoryCoherenceReceiverUsefulnessRepeatabilityArtifact(artifact), []);
mkdirSync('evidence', { recursive: true });
writeFileSync('evidence/passive-live-memory-coherence-receiver-usefulness-repeatability-scorecard-reviewer-package-v0.43.5.out.json', `${JSON.stringify(artifact, null, 2)}\n`);
writeFileSync('evidence/passive-live-memory-coherence-receiver-usefulness-repeatability-scorecard-report-v0.43.5.out.md', `${artifact.reportMarkdown}\n`);
assert.equal(Object.hasOwn(artifact.protocol, 'policyDecision'), false);
assert.equal(Object.hasOwn(artifact.metrics, 'policyDecision'), false);
assert(artifact.repeatabilityRuns.every((run) => run.judgements.every((judgement) => Object.hasOwn(judgement, 'policyDecision') === false)));
console.log(JSON.stringify({ repeatabilityStatus: artifact.repeatabilityStatus, stableCandidateCount: artifact.metrics.stableCandidateCount }, null, 2));
