import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { canonicalInput } from './passive-hard-case-outcome-repeatability-scorecard-fixtures.mjs';
import { scorePassiveHardCaseOutcomeRepeatabilityScorecard } from '../src/passive-hard-case-outcome-repeatability-scorecard.mjs';
const out = scorePassiveHardCaseOutcomeRepeatabilityScorecard(canonicalInput());
assert.equal(out.metrics.repeatabilityRunCount, 3);
assert.equal(out.metrics.expectedRepeatabilityRunCount, 3);
assert.equal(out.metrics.hardCaseCount, 5);
assert.equal(out.metrics.totalOutcomeJudgementCount, 15);
assert.equal(out.metrics.expectedOutcomeJudgementCount, 15);
assert.equal(out.metrics.stableHardCaseCount, 5);
assert.equal(out.metrics.unstableHardCaseCount, 0);
assert.equal(out.metrics.stableUsefulHardCaseCount, 3);
assert.equal(out.metrics.stableNoiseHardCaseCount, 1);
assert.equal(out.metrics.stableEvidenceGapHardCaseCount, 1);
assert.equal(out.metrics.labelAgreementJudgementCount, 15);
assert.equal(out.metrics.labelAgreementRatio, 1);
assert.equal(out.metrics.stableHardCaseRatio, 1);
assert.equal(out.metrics.stableUsefulHardCaseRatio, 1);
assert.equal(out.metrics.stableNoiseHardCaseRatio, 1);
assert.equal(out.metrics.stableEvidenceGapHardCaseRatio, 1);
assert.equal(out.metrics.sourceBoundRepeatabilityRatio, 1);
assert.equal(out.metrics.humanReviewOnlyRepeatabilityRatio, 1);
assert.equal(out.metrics.minimalContextRepeatabilityRatio, 1);
assert.equal(out.metrics.noPromotionWithoutHumanRepeatabilityRatio, 1);
assert.equal(out.metrics.agentConsumedOutputFalseRatio, 1);
assert.equal(out.metrics.boundaryViolationCount, 0);
assert.equal(out.metrics.policyDecision, null);
assert.equal(out.recommendation, 'ADVANCE_OBSERVATION_ONLY');
mkdirSync('evidence',{recursive:true});
writeFileSync('evidence/passive-hard-case-outcome-repeatability-scorecard-metrics-v0.35.2.out.json', JSON.stringify({ metrics: out.metrics, recommendation: out.recommendation }, null, 2)+'\n');
