import assert from 'node:assert/strict';
import { scorePassiveLiveMemoryCoherenceReceiverLiveContextHandoffUtility } from '../src/passive-live-memory-coherence-receiver-live-context-handoff-utility.mjs';
import { receiverLiveContextHandoffUtilityInputV046 } from './passive-live-memory-coherence-receiver-live-context-handoff-utility-fixtures.mjs';
const artifact = scorePassiveLiveMemoryCoherenceReceiverLiveContextHandoffUtility(receiverLiveContextHandoffUtilityInputV046());
const m = artifact.metrics;
assert.equal(m.sourceRepeatabilityRunCount, 3);
assert.equal(m.sourceStableObservationCount, 5);
assert.equal(m.sourceUnstableObservationCount, 0);
assert.equal(m.handoffWindowCount, 1);
assert.equal(m.handoffItemCount, 5);
assert.equal(m.includedForLiveContextCount, 4);
assert.equal(m.excludedAsStaleCount, 1);
assert.equal(m.contradictionCautionCount, 1);
assert.equal(m.receiverUsefulHandoffItemCount, 4);
assert.equal(m.receiverNoisyHandoffItemCount, 0);
assert.equal(m.rawSignalUsefulHandoffItemCount, 3);
assert.equal(m.rawSignalNoisyHandoffItemCount, 2);
assert.equal(m.scorecardUsefulHandoffItemCount, 3);
assert.equal(m.scorecardNoisyHandoffItemCount, 2);
assert.equal(m.receiverUsefulnessRatio, 1);
assert.equal(m.rawSignalUsefulnessRatio, 0.6);
assert.equal(m.scorecardUsefulnessRatio, 0.6);
assert.equal(m.sourceBoundHandoffRatio, 1);
assert.equal(m.staleSuppressionUsefulRatio, 1);
assert.equal(m.contradictionCautionUsefulRatio, 1);
assert.equal(m.boundaryViolationCount, 0);
assert.equal(artifact.recommendation, 'ADVANCE_OBSERVATION_ONLY');
console.log(JSON.stringify({ metrics: m }));
