import assert from 'node:assert/strict';
import { scorePassiveLiveMemoryCoherenceStableInvalidationReceiverPackage } from '../src/passive-live-memory-coherence-stable-invalidation-receiver-package.mjs';
import { stableInvalidationReceiverPackageInputV041 } from './passive-live-memory-coherence-stable-invalidation-receiver-package-fixtures.mjs';

const { metrics, policyDecision, recommendation } = scorePassiveLiveMemoryCoherenceStableInvalidationReceiverPackage(stableInvalidationReceiverPackageInputV041());
assert.equal(metrics.receiverPackageItemCount, 5);
assert.equal(metrics.stableCarryForwardItemCount, 3);
assert.equal(metrics.stableStaleInvalidatedItemCount, 1);
assert.equal(metrics.stableContradictionCautionItemCount, 1);
assert.equal(metrics.includedForHumanHandoffCount, 4);
assert.equal(metrics.excludedAsStaleCount, 1);
assert.equal(metrics.sourceBoundItemRatio, 1);
assert.equal(metrics.stableSignalRatio, 1);
assert.equal(metrics.redactedBeforePersistRatio, 1);
assert.equal(metrics.noPromotionWithoutHumanRatio, 1);
assert.equal(metrics.agentConsumedOutputFalseRatio, 1);
assert.equal(metrics.preReadPathPinned, true);
assert.equal(metrics.boundaryViolationCount, 0);
assert.equal(metrics.policyDecision, null);
assert.equal(policyDecision, null);
assert.equal(recommendation, 'ADVANCE_OBSERVATION_ONLY');
console.log(JSON.stringify({ recommendation, metrics }));
