import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { passiveMemoryRecallUsefulnessProtocol } from '../src/passive-memory-recall-usefulness-probe.mjs';

await mkdir(resolve('evidence'), { recursive: true });
const protocol = passiveMemoryRecallUsefulnessProtocol();
assert.equal(protocol.releaseLayer, 'v0.28.0-alpha');
assert.equal(protocol.barrierCrossed, 'passive_memory_recall_usefulness_probe_for_ai_continuity');
assert.equal(protocol.disabledByDefault, true);
assert.equal(protocol.operatorRunOneShotOnly, true);
assert.equal(protocol.localOnly, true);
assert.equal(protocol.passiveOnly, true);
assert.equal(protocol.readOnly, true);
assert.equal(protocol.humanReadableReportOnly, true);
assert.equal(protocol.nonAuthoritative, true);
assert.equal(protocol.recommendationIsAuthority, false);
assert.equal(protocol.noMemoryWrites, true);
assert.equal(protocol.noRuntimeIntegration, true);
assert.equal(protocol.policyDecision, null);
await writeFile(resolve('evidence/passive-memory-recall-usefulness-probe-protocol-v0.28.0-alpha.out.json'), JSON.stringify(protocol, null, 2) + '\n');
console.log(JSON.stringify({ releaseLayer: protocol.releaseLayer, policyDecision: protocol.policyDecision }, null, 2));
