import assert from 'node:assert/strict';
import { scorePassiveLiveMemoryCoherenceRuntimeContextInjectionRehearsal } from '../src/passive-live-memory-coherence-runtime-context-injection-rehearsal.mjs';
import { runtimeContextInjectionRehearsalInputV049 } from './passive-live-memory-coherence-runtime-context-injection-rehearsal-fixtures.mjs';
const m = scorePassiveLiveMemoryCoherenceRuntimeContextInjectionRehearsal(runtimeContextInjectionRehearsalInputV049()).metrics;
assert.equal(m.sourceRuntimeContextCardCount, 5);
assert.equal(m.sourceHarnessConsumableCandidateCount, 4);
assert.equal(m.sourceRuntimeBridgeSignalCount, 4);
assert.equal(m.sourceRuntimeBlockedUntilNextBarrierCount, 5);
assert.equal(m.sourceBoundaryViolationCount, 0);
assert.equal(m.contextCardsConsumedByLocalRehearsalCount, 5);
assert.equal(m.injectionEnvelopeCount, 1);
assert.equal(m.injectionEnvelopeContextBlockCount, 4);
assert.equal(m.receiverFacingContextBlockCount, 4);
assert.equal(m.allEffectsBlockedUntilNextBarrierCount, 10);
assert.equal(m.blockedEffectKindCount, 10);
assert.equal(m.forbiddenEffectCount, 0);
assert.equal(m.sourceBoundContextCardRatio, 1);
assert.equal(m.sourceBoundReceiverBlockRatio, 1);
assert.equal(m.boundaryViolationCount, 0);
console.log(JSON.stringify(m));
