import assert from 'node:assert/strict';
import { scorePassiveLiveMemoryCoherenceReceiverLiveContextHandoffUtility, validatePassiveLiveMemoryCoherenceReceiverLiveContextHandoffUtilityArtifact, passiveLiveMemoryCoherenceReceiverLiveContextHandoffUtilityReport } from '../src/passive-live-memory-coherence-receiver-live-context-handoff-utility.mjs';
import { receiverLiveContextHandoffUtilityInputV046 } from './passive-live-memory-coherence-receiver-live-context-handoff-utility-fixtures.mjs';
const artifact = scorePassiveLiveMemoryCoherenceReceiverLiveContextHandoffUtility(receiverLiveContextHandoffUtilityInputV046());
assert.deepEqual(validatePassiveLiveMemoryCoherenceReceiverLiveContextHandoffUtilityArtifact(artifact), []);
assert.equal(artifact.reportMarkdown, passiveLiveMemoryCoherenceReceiverLiveContextHandoffUtilityReport(artifact));
assert.equal(artifact.policyDecision, null);
assert.equal(artifact.recommendationIsAuthority, false);
assert.equal(artifact.agentConsumedOutput, false);
assert.equal(artifact.noMemoryWrites, true);
assert.equal(artifact.noRuntimeIntegration, true);
assert.equal(artifact.rawPersisted, false);
assert(artifact.handoffItems.every((j) => j.promoteToMemory === false && j.agentConsumedOutput === false));
assert.equal(Object.hasOwn(artifact.protocol, 'policyDecision'), false);
assert.equal(Object.hasOwn(artifact.metrics, 'policyDecision'), false);
assert(artifact.handoffItems.every((item) => Object.hasOwn(item, 'policyDecision') === false));
assert(artifact.reportMarkdown.includes('policyDecision: null'));
console.log(JSON.stringify({ outputBoundary: 'ok', status: artifact.handoffUtilityStatus }));
